/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CTRZGtFokI3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function V5() {
  return (
    <div className="min-h-screen bg-[#f9f3e8]">
      <div className="text-center pt-10">
        <h2 className="text-3xl font-bold">How to Buy?</h2>
      </div>
      <div className="flex justify-center mt-10 space-x-6">
        <div className="relative bg-white p-4 shadow-md rounded-lg transform rotate-2">
          <h3 className="text-xl font-bold">Create wallet</h3>
          <p className="text-sm mt-2">Lorem ipsum dolor sit, amet consectetur adipisicing</p>
          <div className="absolute top-2 right-2 text-4xl font-bold text-gray-300">
            <ArrowRightIcon className="w-8 h-8" />
          </div>
        </div>
        <div className="relative bg-white p-4 shadow-md rounded-lg transform -rotate-2">
          <h3 className="text-xl font-bold">Get some sol</h3>
          <p className="text-sm mt-2">Lorem ipsum dolor sit, amet consectetur adipisicing</p>
          <div className="absolute top-2 right-2 text-4xl font-bold text-gray-300">
            <ArrowRightIcon className="w-8 h-8" />
          </div>
        </div>
        <div className="relative bg-white p-4 shadow-md rounded-lg transform rotate-2">
          <h3 className="text-xl font-bold">Go to raydium</h3>
          <p className="text-sm mt-2">Lorem ipsum dolor sit, amet consectetur adipisicing</p>
          <div className="absolute top-2 right-2 text-4xl font-bold text-gray-300">
            <ArrowRightIcon className="w-8 h-8" />
          </div>
        </div>
        <div className="relative bg-white p-4 shadow-md rounded-lg transform -rotate-2">
          <h3 className="text-xl font-bold">Get your share</h3>
          <p className="text-sm mt-2">Lorem ipsum dolor sit, amet consectetur adipisicing</p>
          <div className="absolute top-2 right-2 text-4xl font-bold text-gray-300">
            <ArrowRightIcon className="w-8 h-8" />
          </div>
        </div>
      </div>
      <div className="mt-10 bg-[#fcbf49] p-6 rounded-lg shadow-md flex items-center justify-between">
        <div>
          <h3 className="text-2xl font-bold">Join our Community</h3>
          <p className="mt-2">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae ullam ipsum rerum autem, deleniti fugiat
            numquam
          </p>
          <div className="flex space-x-4 mt-4">
            <Button variant="outline" className="p-2">
              <XIcon className="w-6 h-6" />
            </Button>
            <Button variant="outline" className="p-2">
              <ArrowLeftIcon className="w-6 h-6" />
            </Button>
            <Button variant="outline" className="p-2">
              <GitlabIcon className="w-6 h-6" />
            </Button>
          </div>
        </div>
        <div>
          <img src="/placeholder.svg" alt="Cat" className="w-40 h-40 object-cover rounded-full" />
        </div>
      </div>
      <footer className="bg-black text-white p-4 mt-10 flex justify-between items-center">
        <div>
          <img src="/placeholder.svg" alt="Solzio Cat" className="w-20" />
        </div>
        <div className="flex space-x-4">
          <Button variant="ghost" className="p-2">
            <MailIcon className="w-6 h-6" />
          </Button>
          <Button variant="ghost" className="p-2">
            <XIcon className="w-6 h-6" />
          </Button>
          <Button variant="ghost" className="p-2">
            <LinkedinIcon className="w-6 h-6" />
          </Button>
        </div>
      </footer>
    </div>
  )
}

function ArrowLeftIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function ArrowRightIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function GitlabIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>
  )
}


function LinkedinIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
